version: '3.8'

services:
  chopsticks-polkadot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chopsticks-polkadot
    ports:
      - "8000:8000"
    volumes:
      - ./pd.yml:/app/config.yml
    command: ["chopsticks", "-c", "/app/config.yml", "-p", "8000", "--addr", "0.0.0.0"]

  chopsticks-statemint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chopsticks-statemint
    ports:
      - "9000:9000"
    volumes:
      - ./pd-ah.yml:/app/config.yml
    command: ["chopsticks", "-c", "/app/config.yml", "-p", "9000", "--addr", "0.0.0.0"]
