[package]
name = "kalatori"
authors = ["Alzymologist Oy <contact@zymologia.fi>"]
version = "0.2.0"
edition = "2021"
description = "A gateway daemon for Kalatori."
license = "GPL-3.0-or-later"
repository = "https://github.com/Alzymologist/Kalatori-backend"
readme = true
keywords = ["substrate", "blockchain", "finance", "service", "middleware"]
categories = ["finance"]

[dependencies]
env_logger = { version = "0.11", default-features = false, features = ["humantime", "auto-color"] }
toml_edit = { version = "0.22", default-features = false, features = ["parse", "serde"] }
axum = { version = "0.7", default-features = false, features = ["tokio", "http1", "query", "json", "matched-path"] }

subxt = { version = "=0.35", features = ["substrate-compat", "unstable-reconnecting-rpc-client"] }
tokio-util = { version = "0.7", features = ["rt"] }
tokio = { version = "1", features = ["signal"] }

ureq = { version = "2", default-features = false }
names = { version = "0.14", default-features = false }

hex-simd = "0.8"
serde = "1"
anyhow = "1"
log = "0.4"
redb = "2"
humantime = "2"

[profile.release]
strip = true
lto = true
codegen-units = 1

[lints.rust]
future_incompatible = "warn"
let_underscore = "warn"
rust_2018_idioms = "warn"
unused = "warn"

[lints.clippy]
shadow_reuse = "warn"
shadow_same = "warn"
shadow_unrelated = "warn"
cargo_common_metadata = "warn"
arithmetic_side_effects = "warn"
pedantic = "warn"
