account-lifetime = 86400000 # 1 day.
depth = 3600000 # 1 hour.
debug = true

[[chain]]
name = "polkadot"
native-token = "DOT"
decimals = 10
endpoints = [
    "ws://chopsticks-polkadot:8000",
]

[[chain]]
name = "statemint"
endpoints = [
    "ws://chopsticks-statemint:9000",
]

[[chain.asset]]
name = "USDC"
id = 1337

[[chain.asset]]
name = "USDt"
id = 1984
