account-lifetime = 86400000 # 1 day.
depth = 3600000 # 1 hour.
debug = true
in-memory-db = true

[[chain]]
name = "chop-assethub-polkadot"
endpoints = [
    "ws://localhost:8000"
]

[[chain.asset]]
name = "USDC"
id = 1337

[[chain.asset]]
name = "USDT"
id = 1984
