account-lifetime = 86400000 # 1 day.
depth = 3600000 # 1 hour.
debug = true

[[chain]]
name = "polkadot"
native-token = "DOT"
decimals = 10
endpoints = [
    "ws://localhost:8000",
    "ws://localhost:8500",
]

[[chain]]
name = "statemint"
endpoints = [
    "ws://localhost:9000",
    "ws://localhost:9500",
]

[[chain.asset]]
name = "USDC"
id = 1337

[[chain.asset]]
name = "USDt"
id = 1984
