account-lifetime = 604800000 # 1 week.
invoices-sweep-trigger = 3600000 # 1 hour.

[[chain]]
name = "kusama"
native-token = "KSM"
decimals = 12
endpoints = [
    "wss://kusama-rpc.polkadot.io",
    "wss://1rpc.io/ksm",
]
