name:                         Rust cargo build and draft release

on:
  push:
    branches:
      - main

jobs:
  cargo-build:
    name:                     Cargo build
    runs-on:                  ubuntu-latest
    env:
      GH_TOKEN:               ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name:                 Cancel Previous Runs
        uses:                 styfle/cancel-workflow-action@0.12.1
        with:
          access_token:       ${{ github.token }}

      - name:                 Checkout sources
        uses:                 actions/checkout@v4.2.1
        with:
          fetch-depth:        50
          submodules:         'recursive'

      - name:                 Install Rust stable toolchain
        uses:                 actions-rs/toolchain@v1.0.7
        with:
          profile:            minimal
          toolchain:          stable
          override:           true

      - name:                 Rust Cache
        uses:                 Swatinem/rust-cache@v2.7.5

      - name:                 cargo build
        run:                  cargo build --release

      - name:                 Get package version
        run:                  >
                              echo "VERSION=$(
                              cargo metadata --format-version=1 --no-deps |
                              jq -r '.packages[] | select(.name == "kalatori") | .version'
                              )" >> $GITHUB_ENV

      - name:                 Draft release binary
        run:                  gh release create -d $VERSION ./target/release/kalatori --generate-notes